### ISSUE TITLE
KawaiiWarning~~

### ISSUE THREAD

**Issue by mystrangeaddiction** [CollabVM-Unofficial/GuacUtils#8]
Hai, linuks-kun~~! Watashi wa name is: Kawaiichan. You have'd been warned for excesive Pussy Pussy Pussy Dabadabdaada technology Usage!!

**Comment by shihakyoritai** [comment]
bye

**Comment by mystrangeaddiction** [comment]
hai ^_^

**Comment by Sycration** [comment]
Are you on cocaine

**Comment by mystrangeaddiction** [comment]
w-w-what is cocin ?? .w.

**Comment by shihakyoritai** [comment]
^ their 9 years old

**Comment by mystrangeaddiction** [comment]
w-w-wat is nin yir od?? ^_^

**Comment by mystrangeaddiction** [comment]
I Am Not 9 yaers old i am kawaii

**Comment by Sycration** [comment]
Cocaine is a drug that makes people act like you. It's the only reasonable explanation. Or maybe all weeaboo types are actually mentally insane
